export const YOUTUBE_SLIDER_ITEM_HALF_WIDTH = 408;
export const YOUTUBE_MOBILE_SLIDER_ITEM_HALF_WIDTH = 107;
export const YOUTUBE_SLIDER_WIDTH = 408;
export const TRACK_INTRODUCE_SLIDER_WIDTH = 1648;
export const TRACK_INTRODUCE_SLIDER_HALF_WIDTH = 268;
export const TRACK_INTRODUCE_MOBILE_SLIDER_ITEM_HALF_WIDTH = 137;
